[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers.docker]
  network = "web"
  endpoint = "unix:///var/run/docker.sock"

[certificatesResolvers.letsencrypt.acme]
  email = "{{ acme_email }}"
  storage = "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "http"
